version: "3.3"

services:
  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - ./db-data:/var/lib/mysql
  web:
    build: . # Current directory
    # command: "scripts/wait-for-it.sh -t 120 db:3306 -- scripts/entrypoint"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
